name: Code analysis

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "auth/**"
      - "comments/**"
      - "posts/**"
      - "gateway/**"
  pull_request:
    branches: ["main"]
    paths:
      - "auth/**"
      - "comments/**"
      - "posts/**"
      - "gateway/**"
      
jobs:
    Analysis:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
  
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}