name: Post Service CI

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Code Analysis"]
    types:
      - completed
  push:
    branches:
      - "*" 
    paths:
      - "posts/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "posts/**"
    

      
jobs:

  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x,  21.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./posts
      run: npm ci

    - name: Build run
      working-directory: ./posts
      run: npm run build --if-present
      env:
        CI: ""

    # - name: Test run
    #   working-directory: ./posts
    #   run: npm test -- --watchAll=false
    #   env:
    #     CI: ""

    
  Build-image:
    needs: [Build]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:posts"
        push: true
        tags: tonyq2k3/post-microservice:${{ github.ref_name }}