name: Test environment deployment

on:
    push:
        branches: ["test"]
        paths:
            - "src/**"
            - "**/*.js"

jobs:
    Build-image:
        runs-on: ubuntu-latest
        steps:
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   
                name: Setup image tag
                run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
            -
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                    push: true
                    tags: tonyq2k3/post-microservice:test-${SHORT_SHA}
        
    Update-manifest:
        runs-on: ubuntu-latest
        needs: Build-image
        if: ${{ success() }}
        steps:
            -
                name: Checkout infrastructure repo
                uses: actions/checkout@v3
                with:
                    repository: NT114-DevOps/infrastructures
                    ref: 'main'
                    token: ${{ secrets.GIT_TOKEN }}

            -   
                name: Setup image tag
                run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
            -
                name: Update frontend manifest
                run: |
                    git config --global user.email "ntbquoc2015@gmail.com"
                    git config --global user.name "TonyQ2k3"
                    echo "Update frontend version to test-${SHORT_SHA}"
                    sed -i 's#tonyq2k3/post-microservice:[^[:space:]]*$#tonyq2k3/post-microservice:test-${SHORT_SHA}#g' ./test/microservices/post-service-deploy.yaml
                    git add ./test/microservices/post-service-deploy.yaml
                    git commit -m "Update post service version to test-${SHORT_SHA} in test environment"
                    git push origin main
